const subjects = [
    "Accounting",
    "African American Studies",
    "Arts, Letters, and Enterprise",
    "Anthropology",
    "Arabic",
    "Art",
    "Art History",
    "Business Analytics & Tech.",
    "Biomathematics",
    "Biology",
    "Business",
    "Chemistry",
    "Chinese",
    "Culture & Language Across Curr",
    "Classics",
    "Comparative Literature",
    "Communication",
    "Computer Science",
    "Drama-See Theatre",
    "East Asian Studies",
    "Economics",
    "Education",
    "School Leadership",
    "English",
    "Engineering Science",
    "Entrepreneurship",
    "Environmental Studies",
    "School Psychology",
    "Film Studies",
    "Finance",
    "French",
    "First Year Experience",
    "Geoscience",
    "German",
    "Global Latinx Studies",
    "General Education",
    "Greek",
    "German Studies",
    "Health Care Administration",
    "Health Care Admin - Exec Prog",
    "Human Communication",
    "History",
    "Human Resource Management",
    "Humanities",
    "International Business",
    "International Studies",
    "Italian",
    "Japanese",
    "Latin",
    "Linguistics",
    "Mathematics",
    "Medieval & Renaissance Studies",
    "Management",
    "Management Information Systems",
    "Marketing",
    "Modern Languages & Literature",
    "Music",
    "Music Ensembles",
    "Applied Music",
    "Neuroscience",
    "Physical Education",
    "Philosophy",
    "Physics",
    "Political Science",
    "Psychology",
    "Religion",
    "Russian",
    "Scientific Computing",
    "Self-Instructional Language",
    "Sociology",
    "Spanish",
    "Speech-See Human Communication",
    "Sport Management",
    "Test Only",
    "Women and Gender Studies",
    "Theatre",
    "Urban Studies",
  ];
const levels = ['1000','2000','3000','4000'] 
const days = ['M','T','W','Th','F'] 
const pathways = ["Humanities","Creative Expression","Social/Behavioral Sciences","Natural Sciences","Quantitative Reasoning"
                  , "Written Communication", "Oral and Visual Communication","Digital Literacy","Global Awareness",
                  "Understanding Diversity", "Foreign Language", "Historical Perspective", "Fitness Education"]


module.exports = {subjects, levels, days,pathways}